<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ru.ifmo.cs</groupId>
        <artifactId>BasicComputer</artifactId>
        <version>2.45</version>
    </parent>
    <groupId>ru.ifmo.cs</groupId>
    <artifactId>bcomp-ng-ui</artifactId>
    <name>BasicComputer NextGen SWING and CLI UI</name>
    <url>https://se.ifmo.ru/courses/csbasics</url>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <minimizeJar>false</minimizeJar>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>ru.ifmo.cs.bcomp.ui.BCompApp</mainClass>
                                </transformer>
                            </transformers>
                            <artifactSet>
                                <includes>
                                    <include>ru.ifmo.cs:components</include>
                                    <include>ru.ifmo.cs:bcomp-assembler</include>
                                    <include>ru.ifmo.cs:bcomp-ng</include>
                                    <include>ru.ifmo.cs:bcomp-axl</include>
                                    <include>ru.ifmo.cs:bcomp-ng-ui</include>
                                    <include>org.antlr:antlr4-runtime</include>
                                </includes>
                            </artifactSet>
                            <finalName>../../bcomp-ng-app-${project.version}</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>components</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>bcomp-ng</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>bcomp-assembler</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>bcomp-axl</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
