#!/bin/sh
# $Id$

MODE=gui
JAR=bcomp-ng.jar

while getopts gcdnp: arg
do
	case "$arg" in
	g)	MODE=gui;;
	c)	MODE=cli;;
	d)	MODE=decoder;;
	n)	MODE=nightmare;;
	p)	JAR="$OPTARG";;
	*)
		echo "Usage: bcomp [-g | -c | -d] [-b | -o | -e] [-p path]
	-g - run in GUI mode (default)
	-c - run in CLI mode
	-n - run in nightmare mode
	-d - run microprogram decoder
	-p path - path to bcomp.jar"
		exit 1
	esac
done

java -server -Dmode=$MODE -jar "$JAR"
