name: "Build and upload artifacts"

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{github.ref_name}}
        files: bcomp-ng-ui/target/bcomp-ng.jar
